"""empty message

Revision ID: 05218f4c58b7
Revises: 082fc9ce77b7
Create Date: 2025-02-24 11:36:03.286789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05218f4c58b7'
down_revision = '082fc9ce77b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer_job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('experience_level', sa.String(length=100), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('estimated_salary_from', sa.Float(), nullable=True),
    sa.Column('estimated_salary_to', sa.Float(), nullable=True),
    sa.Column('no_of_vacancies', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city_municipality', sa.String(length=100), nullable=False),
    sa.Column('other_skills', sa.Text(), nullable=True),
    sa.Column('course_name', sa.String(length=255), nullable=True),
    sa.Column('training_institution', sa.String(length=255), nullable=True),
    sa.Column('certificate_received', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employer_job_postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employer_job_postings_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employer_job_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employer_job_postings_user_id'))

    op.drop_table('employer_job_postings')
    # ### end Alembic commands ###
