"""empty message

Revision ID: 0659f740af21
Revises: 51106666f0e5
Create Date: 2025-02-10 08:55:10.977089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0659f740af21'
down_revision = '51106666f0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language_proficiency', schema=None) as batch_op:
        batch_op.alter_column('can_understand',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language_proficiency', schema=None) as batch_op:
        batch_op.alter_column('can_understand',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
