"""empty message

Revision ID: 082fc9ce77b7
Revises: 5d4925924caa
Create Date: 2025-02-17 15:41:28.662559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082fc9ce77b7'
down_revision = '5d4925924caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker_student_personal_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker_student_personal_information', schema=None) as batch_op:
        batch_op.drop_column('prefix')

    # ### end Alembic commands ###
