"""empty message

Revision ID: 1c00cc9b5339
Revises: cc1b310d34bb
Create Date: 2025-02-13 17:04:31.138781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c00cc9b5339'
down_revision = 'cc1b310d34bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academe_personal_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('suffix', sa.String(length=10), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('institution_type', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('employer_position', sa.String(length=100), nullable=False),
    sa.Column('employer_id_number', sa.String(length=100), nullable=False),
    sa.Column('temporary_country', sa.String(length=100), nullable=False),
    sa.Column('temporary_province', sa.String(length=100), nullable=True),
    sa.Column('temporary_municipality', sa.String(length=100), nullable=True),
    sa.Column('temporary_zip_code', sa.String(length=10), nullable=True),
    sa.Column('temporary_barangay', sa.String(length=100), nullable=True),
    sa.Column('temporary_house_no_street_village', sa.String(length=255), nullable=True),
    sa.Column('permanent_country', sa.String(length=100), nullable=True),
    sa.Column('permanent_province', sa.String(length=100), nullable=True),
    sa.Column('permanent_municipality', sa.String(length=100), nullable=True),
    sa.Column('permanent_zip_code', sa.String(length=10), nullable=True),
    sa.Column('permanent_barangay', sa.String(length=100), nullable=True),
    sa.Column('permanent_house_no_street_village', sa.String(length=255), nullable=True),
    sa.Column('cellphone_number', sa.String(length=20), nullable=False),
    sa.Column('landline_number', sa.String(length=20), nullable=True),
    sa.Column('valid_id_uri', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('academe_personal_information')
    # ### end Alembic commands ###
