"""empty message

Revision ID: 45faee9aba7d
Revises: cb4451192c01
Create Date: 2025-02-09 23:58:26.026804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45faee9aba7d'
down_revision = 'cb4451192c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language_proficiency', schema=None) as batch_op:
        batch_op.drop_column('proficiency_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language_proficiency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proficiency_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
