"""empty message

Revision ID: 471c2b908a2f
Revises: 8c45645a5306
Create Date: 2025-02-11 17:05:01.101116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471c2b908a2f'
down_revision = '8c45645a5306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker_student_job_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('municipality', sa.String(length=100), nullable=False))
        batch_op.drop_column('city_municipality')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker_student_job_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_municipality', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('municipality')
        batch_op.drop_column('province')

    # ### end Alembic commands ###
