"""empty message

Revision ID: 51106666f0e5
Revises: 45faee9aba7d
Create Date: 2025-02-10 08:54:35.712101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51106666f0e5'
down_revision = '45faee9aba7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language_proficiency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_write', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_speak', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_understand', sa.Boolean(), nullable=True))
        batch_op.drop_column('additional_details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language_proficiency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_details', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('can_understand')
        batch_op.drop_column('can_speak')
        batch_op.drop_column('can_write')
        batch_op.drop_column('can_read')

    # ### end Alembic commands ###
