"""empty message

Revision ID: 55f47b1e6f99
Revises: 63807607dab7
Create Date: 2025-02-11 15:42:00.809511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f47b1e6f99'
down_revision = '63807607dab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker_student_personal_information', schema=None) as batch_op:
        batch_op.alter_column('religion',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker_student_personal_information', schema=None) as batch_op:
        batch_op.alter_column('religion',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
