"""empty message

Revision ID: 5d4925924caa
Revises: fe08d735c31b
Create Date: 2025-02-13 19:25:05.718425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4925924caa'
down_revision = 'fe08d735c31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer_personal_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('suffix', sa.String(length=10), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_type', sa.String(length=50), nullable=False),
    sa.Column('company_classification', sa.String(length=50), nullable=False),
    sa.Column('company_industry', sa.String(length=50), nullable=False),
    sa.Column('company_workforce', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('employer_position', sa.String(length=100), nullable=False),
    sa.Column('employer_id_number', sa.String(length=100), nullable=False),
    sa.Column('temporary_country', sa.String(length=100), nullable=True),
    sa.Column('temporary_province', sa.String(length=100), nullable=True),
    sa.Column('temporary_municipality', sa.String(length=100), nullable=True),
    sa.Column('temporary_zip_code', sa.String(length=10), nullable=True),
    sa.Column('temporary_barangay', sa.String(length=100), nullable=True),
    sa.Column('temporary_house_no_street_village', sa.String(length=255), nullable=True),
    sa.Column('permanent_country', sa.String(length=100), nullable=True),
    sa.Column('permanent_province', sa.String(length=100), nullable=True),
    sa.Column('permanent_municipality', sa.String(length=100), nullable=True),
    sa.Column('permanent_zip_code', sa.String(length=10), nullable=True),
    sa.Column('permanent_barangay', sa.String(length=100), nullable=True),
    sa.Column('permanent_house_no_street_village', sa.String(length=255), nullable=True),
    sa.Column('cellphone_number', sa.String(length=20), nullable=False),
    sa.Column('landline_number', sa.String(length=20), nullable=True),
    sa.Column('valid_id_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employer_personal_information')
    # ### end Alembic commands ###
