"""empty message

Revision ID: 63807607dab7
Revises: e337aa311d14
Create Date: 2025-02-11 14:52:22.155252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63807607dab7'
down_revision = 'e337aa311d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker_student_personal_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporary_country', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('temporary_province', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('temporary_municipality', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('temporary_zip_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('temporary_barangay', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('temporary_house_no_street_village', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('permanent_country', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('permanent_province', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('permanent_municipality', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('permanent_zip_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('permanent_barangay', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('permanent_house_no_street_village', sa.String(length=255), nullable=True))
        batch_op.drop_column('barangay')
        batch_op.drop_column('province')
        batch_op.drop_column('country')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('municipality')
        batch_op.drop_column('house_no_street_village')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker_student_personal_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('house_no_street_village', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('municipality', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('province', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('barangay', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('permanent_house_no_street_village')
        batch_op.drop_column('permanent_barangay')
        batch_op.drop_column('permanent_zip_code')
        batch_op.drop_column('permanent_municipality')
        batch_op.drop_column('permanent_province')
        batch_op.drop_column('permanent_country')
        batch_op.drop_column('temporary_house_no_street_village')
        batch_op.drop_column('temporary_barangay')
        batch_op.drop_column('temporary_zip_code')
        batch_op.drop_column('temporary_municipality')
        batch_op.drop_column('temporary_province')
        batch_op.drop_column('temporary_country')

    # ### end Alembic commands ###
