"""empty message

Revision ID: b25fa275b5d2
Revises: 0659f740af21
Create Date: 2025-02-10 09:21:25.962679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b25fa275b5d2'
down_revision = '0659f740af21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobseeker_student_job_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city_municipality', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('preferred_occupation', sa.String(length=100), nullable=False),
    sa.Column('salary_from', sa.Float(), nullable=False),
    sa.Column('salary_to', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobseeker_student_language_proficiency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.Column('can_write', sa.Boolean(), nullable=False),
    sa.Column('can_speak', sa.Boolean(), nullable=False),
    sa.Column('can_understand', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobseeker_student_personal_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('place_of_birth', sa.String(length=100), nullable=False),
    sa.Column('civil_status', sa.String(length=20), nullable=False),
    sa.Column('cellphone_number', sa.String(length=15), nullable=False),
    sa.Column('disability', sa.String(length=100), nullable=True),
    sa.Column('employment_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('job_preference')
    op.drop_table('language_proficiency')
    op.drop_table('personal_information')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_information',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('middle_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('sex', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('place_of_birth', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('civil_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('cellphone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('disability', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('employment_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='personal_information_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='personal_information_pkey')
    )
    op.create_table('language_proficiency',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('can_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_write', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_speak', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_understand', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='language_proficiency_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='language_proficiency_pkey')
    )
    op.create_table('job_preference',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('city_municipality', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('preferred_occupation', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('salary_from', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('salary_to', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='job_preference_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='job_preference_pkey')
    )
    op.drop_table('jobseeker_student_personal_information')
    op.drop_table('jobseeker_student_language_proficiency')
    op.drop_table('jobseeker_student_job_preference')
    # ### end Alembic commands ###
