"""empty message

Revision ID: b3d5282c0473
Revises: 1c00cc9b5339
Create Date: 2025-02-13 17:05:29.045323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d5282c0473'
down_revision = '1c00cc9b5339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academe_personal_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_id_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('valid_id_uri')

    with op.batch_alter_table('jobseeker_student_personal_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_id_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('valid_id_uri')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker_student_personal_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_id_uri', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('valid_id_url')

    with op.batch_alter_table('academe_personal_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_id_uri', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('valid_id_url')

    # ### end Alembic commands ###
