"""empty message

Revision ID: e337aa311d14
Revises: f320138a1044
Create Date: 2025-02-11 13:13:42.154472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e337aa311d14'
down_revision = 'f320138a1044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker_student_personal_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phil_health_no', sa.String(length=20), nullable=True))
        batch_op.drop_column('philhealth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker_student_personal_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('philhealth', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('phil_health_no')

    # ### end Alembic commands ###
