"""empty message

Revision ID: ed64bee613c9
Revises: edcad40541b5
Create Date: 2025-02-11 08:14:14.649560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed64bee613c9'
down_revision = 'edcad40541b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker_student_personal_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('religion', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('barangay', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('landline_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tin', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sss_gsis_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pag_ibig_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('philhealth', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_looking_for_work', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_willing_to_work_immediately', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_ofw', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_former_ofw', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_4ps_beneficiary', sa.Boolean(), nullable=False))
        batch_op.alter_column('cellphone_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_jobseeker_student_personal_information_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker_student_personal_information', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobseeker_student_personal_information_user_id'))
        batch_op.alter_column('cellphone_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.drop_column('is_4ps_beneficiary')
        batch_op.drop_column('is_former_ofw')
        batch_op.drop_column('is_ofw')
        batch_op.drop_column('is_willing_to_work_immediately')
        batch_op.drop_column('is_looking_for_work')
        batch_op.drop_column('philhealth')
        batch_op.drop_column('pag_ibig_number')
        batch_op.drop_column('sss_gsis_number')
        batch_op.drop_column('tin')
        batch_op.drop_column('landline_number')
        batch_op.drop_column('address')
        batch_op.drop_column('barangay')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('religion')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
