"""empty message

Revision ID: f320138a1044
Revises: f629d7e9dfbf
Create Date: 2025-02-11 10:57:54.709406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f320138a1044'
down_revision = 'f629d7e9dfbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker_student_personal_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('house_no_street_village', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ofw_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('former_ofw_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('former_ofw_country_date_return', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('_4ps_household_id_no', sa.String(length=50), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker_student_personal_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('_4ps_household_id_no')
        batch_op.drop_column('former_ofw_country_date_return')
        batch_op.drop_column('former_ofw_country')
        batch_op.drop_column('ofw_country')
        batch_op.drop_column('house_no_street_village')

    # ### end Alembic commands ###
