"""empty message

Revision ID: f58d9504c724
Revises: 471c2b908a2f
Create Date: 2025-02-13 07:17:45.636375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58d9504c724'
down_revision = '471c2b908a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker_student_professional_license', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_until', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker_student_professional_license', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('valid_until')

    # ### end Alembic commands ###
