"""empty message

Revision ID: f629d7e9dfbf
Revises: ed64bee613c9
Create Date: 2025-02-11 09:01:07.100628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f629d7e9dfbf'
down_revision = 'ed64bee613c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker_student_personal_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('since_when_looking_for_work', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker_student_personal_information', schema=None) as batch_op:
        batch_op.drop_column('since_when_looking_for_work')

    # ### end Alembic commands ###
