"""empty message

Revision ID: fe08d735c31b
Revises: b3d5282c0473
Create Date: 2025-02-13 18:05:18.595001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe08d735c31b'
down_revision = 'b3d5282c0473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academe_personal_information', schema=None) as batch_op:
        batch_op.alter_column('temporary_country',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academe_personal_information', schema=None) as batch_op:
        batch_op.alter_column('temporary_country',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
